---
abstract: 'add paths to @INC depending on which version of C<perl> is running.'
author:
  - 'Kent Fredric <kentfredric@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0.89'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.039, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: lib-byversion
provides:
  lib::byversion:
    file: lib/lib/byversion.pm
    version: '0.002000'
requires:
  String::Formatter: '0'
  lib: '0'
  perl: '5.006'
  strict: '0'
  version: '0.77'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentfredric/lib-byversion/issues
  homepage: https://github.com/kentfredric/lib-byversion
  repository: https://github.com/kentfredric/lib-byversion.git
version: '0.002000'
